// RESERVACIONES
export const SETDATATOEDITH = "SETDATATOEDITH";
export const RESETDATATOEDITH = "RESETDATATOEDITH";
export const GETDATATOEDITH = "GETDATATOEDITH";

// MOBILIARIO

// PRESENTACION

// USUARIOS
export const SETACTUALUSER = "SETACTUALUSER";
export const UPDATEACTUALUSER = "UPDATEACTUALUSER";
export const RESETACTUALUSER = "RESETACTUALUSER";
